services:
  libretranslate:
    image: libretranslate/libretranslate
    container_name: libretranslate
    ports:
      - "5001:5000"
    environment:
      - LT_DISABLE_API_KEY=true
      - LT_DISABLE_RATE_LIMIT=true
      - LT_DISABLE_ORIGIN_CHECK=true
    restart: unless-stopped
